### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by sulaimanbale11** [NVISO-BE/caldex#1]
May i know how to setup Caldex plug-in in Caldera?

**Comment by 0xThiebaut** [comment]
Hi @sulaimanbale11 ,
Thank you for raising this issue.

I've updated Caldex's [README.md](https://github.com/NVISO-BE/caldex/blob/master/README.md) file to include the beneath information. Could you tell me whether this clears-up any installation questions?

> ## Installation
> 
> Installing Caldex assumes basic knowledge of [Plugins within Caldera](https://github.com/mitre/caldera/wiki/What-is-a-plugin).
> 
> As one would do for any Caldera plugin, installing Caldex can be achieved using the following operations:
> 
> 1. Clone Caldex into Caldera's `plugin` folder using one of the [supported versions](https://github.com/NVISO-BE/caldex/releases) (i.e. `2.3.2`).
> 
>    ```bash
>    # This command assumes "~/caldera" to be Caldera's root.
>    # You might need to change this accordingly (i.e. "/home/user/Downloads/caldera").
>    git clone -C ~/caldera/plugins -b "2.3.2" https://github.com/NVISO-BE/caldex.git
>    ```
> 
> 2. Add Caldex to the enabled plugins in the used Caldera configuration file (i.e. `~/caldera/conf/local.yml`). The following snippet is an example using the default configuration.
> 
>    ```yaml
>    ---
>    
>    host: 0.0.0.0
>    port: 8888
>    exfil_dir: /tmp
>    memory: True
>    untrusted_timer: 180
>    plugins:
>      - stockpile
>      - sandcat
>      - gui
>      - chain
>      - caldex # Insert "caldex" into the list of used plugins.
>    debug: False
>    users:
>      admin: admin
>    ```
> 
> 3. Restart Caldera to apply the configuration changes.

**Comment by sulaimanbale11** [comment]
Thank you very much! Will try it ASAP.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/68337910-6bf2ae80-011c-11ea-9491-efbc63369c6d.png)

I am facing this error while trying out the first command. Any fixes ?

**Comment by 0xThiebaut** [comment]
Hi @sulaimanbale ,

Two things are happening here. First of all I made a mistake with the command. The `-C` switch is relative to the `git` binary and not to the `clone` command. The correct command should hence be the following:
```bash
git -C ~/caldera/plugins clone -b "2.3.2" https://github.com/NVISO-BE/caldex.git
```

Next, I assume from your screenshot that the Caldera root directory is `~/calderanew/caldera` as opposed to the `~/caldera` directory used by the documented command. You should hence adapt the Git command to be the following according to your current setup:
```bash
git -C ~/calderanew/caldera/plugins clone -b "2.3.2" https://github.com/NVISO-BE/caldex.git
```

Let me know if this resolves your issue.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/68351877-bc2f3800-013f-11ea-930c-e76e1bcb3318.png)

![image](https://user-images.githubusercontent.com/46603663/68351934-db2dca00-013f-11ea-8db6-3d3a8a5edabe.png)

Hi, i am getting this page after setting caldex up. The instructions were done rightly and correctly.

**Comment by 0xThiebaut** [comment]
Hi @sulaimanbale ,

The JSON output you are receiving is exactly what the plugin does. What you see is the computed MITRE ATT&CK Navigator Layer which you can save to a file and import it into the [MITRE ATT&CK Navigator](https://mitre-attack.github.io/attack-navigator/enterprise/). I would suggest you read-up on the Navigator's layer documentation from which I find the following excerpt the most relevant:

> # Layers
> A layer constitutes a view of the tactics and techniques matrix for a specific technology domain. Version 2.3.1 of the Navigator can manipulate either the Enterprise (Windows, Linux & Mac) or Mobile (Android & iOS) ATT&CK technology domain knowledge bases. Within a technology domain, the Navigator allows you to filter your view of the matrix in a variety of ways, displaying the tactics and techniques that are important to you.
> 
> You can view the definition of any technique in the visible matrix by right-clicking on the technique and selecting "view technique" in the pop-up menu. A new browser tab will be opened displaying the definition of the technique. In this way the Navigator allows you to explore a given ATT&CK matrix and access the definitions of the techniques.
> 
> Beyond the filters, layers also provide a means to customize your view of the matrix. To that end you can color, hide, comment, and assign numeric scores to techniques to aid in analysis of threats and your defenses against those threats. As stated earlier, the Navigator is designed to be simple, allowing you to assign whatever meaning you want to the color-codings, scores, and comments. This way the Navigator can support whatever you want to do without requiring changes to the Navigator code itself.
> 
> Each layer created is independent of other layers. However, layers can be combined in ways to support analysis, or saved locally. Layer files are saved in easy to parse and easy to generate JSON file so that ATT&CK data can be used in other applications, analyzed beyond the capability of the ATT&CK Navigator, and generated by tools for import into the Navigator. The Layer file format is described here.
> 
>
> ## Creating New Layers
> 
> To create a new layer, open a new tab and click the "Create New Layer" button. Note that for performance reasons, the Navigator currently imposes a limit of ten (10) active layers at any given point in time.
>
> ## Saving and Loading Layers
> 
> Layers can be saved by clicking the "save layer" button (). This will open a dialog to save a layer configuration file to your local computer. This contains the configuration for the techniques that have been customized (commented, colored, assigned a score, or disabled) as well as the scoring gradient setup, filter selection, layer name, layer description, view configuration.
> 
> Saved layer configuration files can be opened in the ATT&CK navigator to restore a layer you've worked on previously. To do so, open a new tab and open the "Open Existing Layer" panel. Then click "Upload from local", and select your saved configuration file. Doing so will restore your saved layer to the ATT&CK navigator. This interface also has a "load from URL" input allowing you to open a layer json from a remote source. 

As your current issue ("How to setup?") seems resolved, I will close this issue. Feel free to open another issue should you encounter other Caldex-related issues.
