### ISSUE TITLE
No attribute "explode_operation"

### ISSUE THREAD

**Issue by ramus82** [NVISO-BE/caldex#2]
Hello guys,
I installed your caldex module into caldera and I'm getting following error when accessing the caldex module in WebUI:
`
Oops...: AttributeError("'DataService' object has no attribute 'explode_operation'")
`
The caldera instance was cloned from mitre and it is running under default configuration. Caldera is running fine (no issues so far).

Is there something particular what shall I check in order to fix this issue?

Thanks a lot.

**Comment by 0xThiebaut** [comment]
Hi @ramus82 ,
Did you properly install Caldera using a [valid release](https://github.com/mitre/caldera/releases) (`2.3.2` is currently the only supported version) instead of the development master branch? To make sure, could you post the full verbose output you get when starting up Caldera?

**Comment by ramus82** [comment]
Hi @0xThiebaut ,
I though that the caldex might work even on devel version. I tried that on devel which was causing the issue described above. On the version 2.3.2 it works fine.

Thank you very much for your help.
Regards
